- !!com.github.athieriot.jtaches.taches.SysoutTache [{
    path: "./src"
}]

- !!com.github.athieriot.jtaches.taches.CopyTache [{
    path: "./src",
    copyTo: "./target",
    makePath: "true"
}]

- !!com.github.athieriot.jtaches.taches.ScriptTache [{
    path: "./src",
    script: "notify-send <path>/<filename>(<shortname>.<ext>)?<event>",
    workingDirectory: "."
}]

- !!com.github.athieriot.jtaches.taches.RabbitmqTache [{
    path: "./src",
    exchangeName: "event_exchange",
    createEventRoutingKey: "create",
    modifyEventRoutingKey: "modify",
    deleteEventRoutingKey: "delete",
    absolutePath: "true",
    #username: "",
    #password: "",
    #virtualHost: "",
    #host: "",
    #port: ""
}]
