- !!com.github.athieriot.jtaches.taches.SysoutTache [{
    path: "./src"
}]

- !!com.github.athieriot.jtaches.taches.CopyTache [{
    path: "./src",
    copyTo: "./target",
    makePath: "true"
}]

- !!com.github.athieriot.jtaches.taches.ScriptTache [{
    path: "./src",
    script: "notify-send <path>/<filename>(<shortname>.<ext>)?<event>",
    workingDirectory: "."
}]
